/*
 * DataContainer.java
 *
 * Created on February 17, 2003, 4:19 PM
 */

package haubold.resources.util;

/**
 *
 * @author  haubold
 * @version
 */
public class DataContainer extends Object {

  /** Creates new DataContainer */
  public DataContainer() {
  }
  /**
  * Drosophila melanogaster alcohol dehydrogenase sequence as published by Kreitman 1983.
  */
  public String getAdh() {
    return ">gi|684943|gb|U20765.1|DMU20765 Drosophila melanogaster alcohol dehydrogenase (Adh) gene, complete cds, and copia insertion site \n"
           + "TGTAAATAAGATTGACTCTTTTTCGATTTTGGAATAGTTTCGTTTCATTCATTATAAGTTTTTACGTTTT"
           + "CACTTATTTGTTTCTCAGTGCACTTTCTGGTGTTCCATTTTCTATTGGGCTCTTTACCCCGCATTTGTTT"
           + "GCAGATCACTTGCTTGCGCATTTTTATTGCATTTTACATATTACACATTATTTGAACGCCGCTGCTGCTG"
           + "CATCCGTCGACGTCGACTGCACTCGCCCCCACGAGAGAACAGTATTTAAGGAGCTGCGAAGGTCCAAGTC"
           + "ACCGATTATTGTCTCAGTGCAGTTGTCAGTTGCAGTTCAGCAGACGGGCTAACGAGTACTTGCATCTCTT"
           + "CAAATTTACTTAATTGATCAAGTAAGTAGCAAAAGGGCACACAATTGAAGGAAATTCTTGTTTAATTGAA"
           + "TTTATTGTGCAAGTGCGGAAATAAAATGACAGGATTGAATAGTAAAATAGTAAAATTGAATTGTAAAATC"
           + "ATATATAATCAAATTTATTCAATCAGAACTAATTCAAGCTGTCACAAGTAGTGCGAACTCAATTAATTGG"
           + "CATCGAATTAAAATTTGGAGGCCTGTGCCGCATATTCGTCTTGGAAAATCACCTGTTAGTTAACTTCTAA"
           + "AAATAGGAATTTTAACATAACTCGTCCCTGTTAATCGGCGCCGTGCCTTCGTTAGCTATCTCAAAAGCGA"
           + "GCGCGTGCAGACGAGCAGTAATTTTCCAAGCATCAGGCATAGTTGGGCATAAATTATAAACATACAAACC"
           + "GAATACTAATATAGAAAAAGCTTTGCCGGTACAAAATCCCAAACAAAAACAAACCGTGTGTGCCGAAAAA"
           + "TAAAAATAAACCATAAACTAGGCAGCGCTGCCGTCGCCGGCTGAGCAGCCTGCGTACATAGCCGAGATCG"
           + "CGTAACGGTAGATAATGAAAAGCTCTACGTAACCGAAGCTTCTGCTGTACGGATCTTCCTATAAATACGG"
           + "GGCCGACACGAACTGGAAACCAACAACTAACGGAGCCCTCTTCCAATTGAAACAGATCGAAAGAGCCTGC"
           + "TAAAGCAAAAAAGAAGTCACCATGTCGTTTACTTTGACCAACAAGAACGTGATTTTCGTTGCCGGTCTGG"
           + "GAGGCATTGGTCTGGACACCAGCAAGGAGCTGCTCAAGCGCGATCTGAAGGTAACTATGCGATGCCCACA"
           + "GGCTCCATGCAGCGATGGAGGTTAATCTCGTGTATTCAATCCTAGAACCTGGTGATCCTCGACCGCATTG"
           + "AGAACCCGGCTGCCATTGCCGAGCTGAAGGCAATCAATCCAAAGGTGACCGTCACCTTCTACCCCTATGA"
           + "TGTGACCGTGCCCATTGCCGAGACCACCAAGCTGCTGAAGACCATCTTCGCCCAGCTGAAGACCGTCGAT"
           + "GTCCTGATCAACGGAGCTGGTATCCTGGACGATCACCAGATCGAGCGCACCATTGCCGTCAACTACACTG"
           + "GCCTGGTCAACACCACGACGGCCATTCTGGACTTCTGGGACAAGCGCAAGGGCGGTCCCGGTGGTATCAT"
           + "CTGCAACATTGGATCCGTCACTGGATTCAATGCCATCTACCAGGTGCCCGTCTACTCCGGCACCAAGGCC"
           + "GCCGTGGTCAACTTCACCAGCTCCCTGGCGGTAAGTTGATCAAAGGAAACGCAAAGTTTTCAAGAAAAAA"
           + "CAAAACTAATTTGATTTATAACACCTTTAGAAACTGGCCCCCATTACCGGCGTGACCGCTTACACTGTGA"
           + "ACCCCGGCATCACCCGCACCACCCTGGTGCACAAGTTCAACTCCTGGTTGGATGTTGAGCCTCAGGTTGC"
           + "CGAGAAGCTCCTGGCTCATCCCACCCAGCCCTCGTTGGCCTGCGCCGAGAACTTCGTCAAGGCTATCGAG"
           + "CTGAACCAGAACGGAGCCATCTGGAAACTGGACTTGGGCACCCTGGAGGCCATCCAGTGGACCAAGCACT"
           + "GGGACTCCGGCATCTAAGAAGTGATACTCCCAAAAAAAAAAAAAACATAACATTAGTTCATAGGGTTCTG"
           + "CGAACCACAAGATATTCACGCAAGGCAATAAGGCTGATTCGATGCACACTCACATTCTTCTCCTAATACG"
           + "ATAATAAAACTTTCCATGAAAAATATGGAAAAATATATGAAAATTGAGAAATCCAAAAAACTGATAAACG"
           + "CTCTACTTAATTAAAATAGATAAATGGGAGCGGCAGGAATGGCGGAGCATGGCCAAGTTCCTCCGCCAAT"
           + "CAGTCGTAAAACAGAAGTCGTGGAAAGCGGATAGAAAGAATGTTCGATTTGACGGGCAAGCATGTCTGCT"
           + "ATGTGGCGGATTGCGGAGGAATTGCACTGGAGACCAGCAAGGTTCTCATGACCAA";
  }

  public String getAdh2() {
    return ">gi|156911|gb|M60791.1|DROADHZB Drosophila adiastola alcohol dehydrogenase gene, complete cds \n"
           + "ATGGTTATCGCTAACAGTAACATCATCTTTGTCGCTGGTCTGGGTGGCATTGGCCTGGACACCAGTCGCG"
           + "AGATTGTCAAGAGTGGCCCCAAGGTAGGTTATAGCCTGTAAATCTCAGGATATAGTATGTAAAAATAAGA"
           + "AAAAAATTCATTATATTTTTTTTTGTCGTTTAGAACCTGGTGTTGCTTGATCGCATTGACAACCCCGCTG"
           + "CCATTGCCGAGTTGAGTGCACTCAATCCTAAGGTGACCGTTACATTCTATCCCTATGATGTTACCGTACC"
           + "GTTGGATGAAACCAAAAAGCTATTGAAGACAATCTTCGACAAGCTGAAGACAGTTGATCTGCTCATCAAT"
           + "GGCGCTGGTATTCTGGACGACAATCAGATTGAGCGCACCATTGCGGTGAATTTTACTGGTACAGTGAACA"
           + "CCACAACTGCGATCATGGATTTCTGGGACAAGCGTAAGGGCGGCCCAGGTGGTGTTGTTGCCAACATCTG"
           + "CTCAGTAACTGGCTTCAACTCCATCTATCAGGTGCCCGTTTACTCTGCCTCAAAGGCAGCTGCCCTAAGT"
           + "TTCACTACTTCCTTTCGGGTAAGTAAATATATAAATATATAAAAATATAATTTTCATCAGGTGGCAACCT"
           + "ATTAAATGTTAACAGAAATTGGCGGGTATTACTGGCGTTACGGCATACTCCATCAATCCGGGCATTACCA"
           + "AGACCGTTCTGGTGCATAAATTTAACTCCTGGCTGGGTGTTGAGCCACGCGTAGCCGAGCTGCTCCTTGA"
           + "GCATCCCACACAGACAACGCTGCAATGCGGACAGAACTTTGTTAAGGCCATTGAGGCCAACCAGAATGGT"
           + "GCCATCTGGAAACTGGATCTTGGCCGTCTGGATGCTATTGAATGGACCAAGCACTGGGACTCCGGCATCT"
           + "AA";

  }

  /**
  * Sequence of the bacteriophage phi-X174 genome sequence as determined by Sanger et al. 1977. This was the first complete
  * genome to be published.
  */
  public String getPhi() {
    return ">gi|216019|gb|J02482.1|PX1CG Bacteriophage phi-X174, complete genome \n"
           + "GAGTTTTATCGCTTCCATGACGCAGAAGTTAACACTTTCGGATATTTCTGATGAGTCGAAAAATTATCTT"
           + "GATAAAGCAGGAATTACTACTGCTTGTTTACGAATTAAATCGAAGTGGACTGCTGGCGGAAAATGAGAAA"
           + "ATTCGACCTATCCTTGCGCAGCTCGAGAAGCTCTTACTTTGCGACCTTTCGCCATCAACTAACGATTCTG"
           + "TCAAAAACTGACGCGTTGGATGAGGAGAAGTGGCTTAATATGCTTGGCACGTTCGTCAAGGACTGGTTTA"
           + "GATATGAGTCACATTTTGTTCATGGTAGAGATTCTCTTGTTGACATTTTAAAAGAGCGTGGATTACTATC"
           + "TGAGTCCGATGCTGTTCAACCACTAATAGGTAAGAAATCATGAGTCAAGTTACTGAACAATCCGTACGTT"
           + "TCCAGACCGCTTTGGCCTCTATTAAGCTCATTCAGGCTTCTGCCGTTTTGGATTTAACCGAAGATGATTT"
           + "CGATTTTCTGACGAGTAACAAAGTTTGGATTGCTACTGACCGCTCTCGTGCTCGTCGCTGCGTTGAGGCT"
           + "TGCGTTTATGGTACGCTGGACTTTGTGGGATACCCTCGCTTTCCTGCTCCTGTTGAGTTTATTGCTGCCG"
           + "TCATTGCTTATTATGTTCATCCCGTCAACATTCAAACGGCCTGTCTCATCATGGAAGGCGCTGAATTTAC"
           + "GGAAAACATTATTAATGGCGTCGAGCGTCCGGTTAAAGCCGCTGAATTGTTCGCGTTTACCTTGCGTGTA"
           + "CGCGCAGGAAACACTGACGTTCTTACTGACGCAGAAGAAAACGTGCGTCAAAAATTACGTGCGGAAGGAG"
           + "TGATGTAATGTCTAAAGGTAAAAAACGTTCTGGCGCTCGCCCTGGTCGTCCGCAGCCGTTGCGAGGTACT"
           + "AAAGGCAAGCGTAAAGGCGCTCGTCTTTGGTATGTAGGTGGTCAACAATTTTAATTGCAGGGGCTTCGGC"
           + "CCCTTACTTGAGGATAAATTATGTCTAATATTCAAACTGGCGCCGAGCGTATGCCGCATGACCTTTCCCA"
           + "TCTTGGCTTCCTTGCTGGTCAGATTGGTCGTCTTATTACCATTTCAACTACTCCGGTTATCGCTGGCGAC"
           + "TCCTTCGAGATGGACGCCGTTGGCGCTCTCCGTCTTTCTCCATTGCGTCGTGGCCTTGCTATTGACTCTA"
           + "CTGTAGACATTTTTACTTTTTATGTCCCTCATCGTCACGTTTATGGTGAACAGTGGATTAAGTTCATGAA"
           + "GGATGGTGTTAATGCCACTCCTCTCCCGACTGTTAACACTACTGGTTATATTGACCATGCCGCTTTTCTT"
           + "GGCACGATTAACCCTGATACCAATAAAATCCCTAAGCATTTGTTTCAGGGTTATTTGAATATCTATAACA"
           + "ACTATTTTAAAGCGCCGTGGATGCCTGACCGTACCGAGGCTAACCCTAATGAGCTTAATCAAGATGATGC"
           + "TCGTTATGGTTTCCGTTGCTGCCATCTCAAAAACATTTGGACTGCTCCGCTTCCTCCTGAGACTGAGCTT"
           + "TCTCGCCAAATGACGACTTCTACCACATCTATTGACATTATGGGTCTGCAAGCTGCTTATGCTAATTTGC"
           + "ATACTGACCAAGAACGTGATTACTTCATGCAGCGTTACCATGATGTTATTTCTTCATTTGGAGGTAAAAC"
           + "CTCTTATGACGCTGACAACCGTCCTTTACTTGTCATGCGCTCTAATCTCTGGGCATCTGGCTATGATGTT"
           + "GATGGAACTGACCAAACGTCGTTAGGCCAGTTTTCTGGTCGTGTTCAACAGACCTATAAACATTCTGTGC"
           + "CGCGTTTCTTTGTTCCTGAGCATGGCACTATGTTTACTCTTGCGCTTGTTCGTTTTCCGCCTACTGCGAC"
           + "TAAAGAGATTCAGTACCTTAACGCTAAAGGTGCTTTGACTTATACCGATATTGCTGGCGACCCTGTTTTG"
           + "TATGGCAACTTGCCGCCGCGTGAAATTTCTATGAAGGATGTTTTCCGTTCTGGTGATTCGTCTAAGAAGT"
           + "TTAAGATTGCTGAGGGTCAGTGGTATCGTTATGCGCCTTCGTATGTTTCTCCTGCTTATCACCTTCTTGA"
           + "AGGCTTCCCATTCATTCAGGAACCGCCTTCTGGTGATTTGCAAGAACGCGTACTTATTCGCCACCATGAT"
           + "TATGACCAGTGTTTCCAGTCCGTTCAGTTGTTGCAGTGGAATAGTCAGGTTAAATTTAATGTGACCGTTT"
           + "ATCGCAATCTGCCGACCACTCGCGATTCAATCATGACTTCGTGATAAAAGATTGAGTGTGAGGTTATAAC"
           + "GCCGAAGCGGTAAAAATTTTAATTTTTGCCGCTGAGGGGTTGACCAAGCGAAGCGCGGTAGGTTTTCTGC"
           + "TTAGGAGTTTAATCATGTTTCAGACTTTTATTTCTCGCCATAATTCAAACTTTTTTTCTGATAAGCTGGT"
           + "TCTCACTTCTGTTACTCCAGCTTCTTCGGCACCTGTTTTACAGACACCTAAAGCTACATCGTCAACGTTA"
           + "TATTTTGATAGTTTGACGGTTAATGCTGGTAATGGTGGTTTTCTTCATTGCATTCAGATGGATACATCTG"
           + "TCAACGCCGCTAATCAGGTTGTTTCTGTTGGTGCTGATATTGCTTTTGATGCCGACCCTAAATTTTTTGC"
           + "CTGTTTGGTTCGCTTTGAGTCTTCTTCGGTTCCGACTACCCTCCCGACTGCCTATGATGTTTATCCTTTG"
           + "AATGGTCGCCATGATGGTGGTTATTATACCGTCAAGGACTGTGTGACTATTGACGTCCTTCCCCGTACGC"
           + "CGGGCAATAACGTTTATGTTGGTTTCATGGTTTGGTCTAACTTTACCGCTACTAAATGCCGCGGATTGGT"
           + "TTCGCTGAATCAGGTTATTAAAGAGATTATTTGTCTCCAGCCACTTAAGTGAGGTGATTTATGTTTGGTG"
           + "CTATTGCTGGCGGTATTGCTTCTGCTCTTGCTGGTGGCGCCATGTCTAAATTGTTTGGAGGCGGTCAAAA"
           + "AGCCGCCTCCGGTGGCATTCAAGGTGATGTGCTTGCTACCGATAACAATACTGTAGGCATGGGTGATGCT"
           + "GGTATTAAATCTGCCATTCAAGGCTCTAATGTTCCTAACCCTGATGAGGCCGCCCCTAGTTTTGTTTCTG"
           + "GTGCTATGGCTAAAGCTGGTAAAGGACTTCTTGAAGGTACGTTGCAGGCTGGCACTTCTGCCGTTTCTGA"
           + "TAAGTTGCTTGATTTGGTTGGACTTGGTGGCAAGTCTGCCGCTGATAAAGGAAAGGATACTCGTGATTAT"
           + "CTTGCTGCTGCATTTCCTGAGCTTAATGCTTGGGAGCGTGCTGGTGCTGATGCTTCCTCTGCTGGTATGG"
           + "TTGACGCCGGATTTGAGAATCAAAAAGAGCTTACTAAAATGCAACTGGACAATCAGAAAGAGATTGCCGA"
           + "GATGCAAAATGAGACTCAAAAAGAGATTGCTGGCATTCAGTCGGCGACTTCACGCCAGAATACGAAAGAC"
           + "CAGGTATATGCACAAAATGAGATGCTTGCTTATCAACAGAAGGAGTCTACTGCTCGCGTTGCGTCTATTA"
           + "TGGAAAACACCAATCTTTCCAAGCAACAGCAGGTTTCCGAGATTATGCGCCAAATGCTTACTCAAGCTCA"
           + "AACGGCTGGTCAGTATTTTACCAATGACCAAATCAAAGAAATGACTCGCAAGGTTAGTGCTGAGGTTGAC"
           + "TTAGTTCATCAGCAAACGCAGAATCAGCGGTATGGCTCTTCTCATATTGGCGCTACTGCAAAGGATATTT"
           + "CTAATGTCGTCACTGATGCTGCTTCTGGTGTGGTTGATATTTTTCATGGTATTGATAAAGCTGTTGCCGA"
           + "TACTTGGAACAATTTCTGGAAAGACGGTAAAGCTGATGGTATTGGCTCTAATTTGTCTAGGAAATAACCG"
           + "TCAGGATTGACACCCTCCCAATTGTATGTTTTCATGCCTCCAAATCTTGGAGGCTTTTTTATGGTTCGTT"
           + "CTTATTACCCTTCTGAATGTCACGCTGATTATTTTGACTTTGAGCGTATCGAGGCTCTTAAACCTGCTAT"
           + "TGAGGCTTGTGGCATTTCTACTCTTTCTCAATCCCCAATGCTTGGCTTCCATAAGCAGATGGATAACCGC"
           + "ATCAAGCTCTTGGAAGAGATTCTGTCTTTTCGTATGCAGGGCGTTGAGTTCGATAATGGTGATATGTATG"
           + "TTGACGGCCATAAGGCTGCTTCTGACGTTCGTGATGAGTTTGTATCTGTTACTGAGAAGTTAATGGATGA"
           + "ATTGGCACAATGCTACAATGTGCTCCCCCAACTTGATATTAATAACACTATAGACCACCGCCCCGAAGGG"
           + "GACGAAAAATGGTTTTTAGAGAACGAGAAGACGGTTACGCAGTTTTGCCGCAAGCTGGCTGCTGAACGCC"
           + "CTCTTAAGGATATTCGCGATGAGTATAATTACCCCAAAAAGAAAGGTATTAAGGATGAGTGTTCAAGATT"
           + "GCTGGAGGCCTCCACTATGAAATCGCGTAGAGGCTTTGCTATTCAGCGTTTGATGAATGCAATGCGACAG"
           + "GCTCATGCTGATGGTTGGTTTATCGTTTTTGACACTCTCACGTTGGCTGACGACCGATTAGAGGCGTTTT"
           + "ATGATAATCCCAATGCTTTGCGTGACTATTTTCGTGATATTGGTCGTATGGTTCTTGCTGCCGAGGGTCG"
           + "CAAGGCTAATGATTCACACGCCGACTGCTATCAGTATTTTTGTGTGCCTGAGTATGGTACAGCTAATGGC"
           + "CGTCTTCATTTCCATGCGGTGCACTTTATGCGGACACTTCCTACAGGTAGCGTTGACCCTAATTTTGGTC"
           + "GTCGGGTACGCAATCGCCGCCAGTTAAATAGCTTGCAAAATACGTGGCCTTATGGTTACAGTATGCCCAT"
           + "CGCAGTTCGCTACACGCAGGACGCTTTTTCACGTTCTGGTTGGTTGTGGCCTGTTGATGCTAAAGGTGAG"
           + "CCGCTTAAAGCTACCAGTTATATGGCTGTTGGTTTCTATGTGGCTAAATACGTTAACAAAAAGTCAGATA"
           + "TGGACCTTGCTGCTAAAGGTCTAGGAGCTAAAGAATGGAACAACTCACTAAAAACCAAGCTGTCGCTACT"
           + "TCCCAAGAAGCTGTTCAGAATCAGAATGAGCCGCAACTTCGGGATGAAAATGCTCACAATGACAAATCTG"
           + "TCCACGGAGTGCTTAATCCAACTTACCAAGCTGGGTTACGACGCGACGCCGTTCAACCAGATATTGAAGC"
           + "AGAACGCAAAAAGAGAGATGAGATTGAGGCTGGGAAAAGTTACTGTAGCCGACGTTTTGGCGGCGCAACC"
           + "TGTGACGACAAATCTGCTCAAATTTATGCGCGCTTCGATAAAAATGATTGGCGTATCCAACCTGCA";
  }

  public String getShakespearePoem() {
    String str =
      "Shall I compare thee to a summer's day"
      + "Thou art more lovely and more temperate:"
      + "Rough winds do shake the darling buds of May,"
      + "And summer's lease hath all too short a date;"
      + "Sometime too hot the eye of heaven shines,"
      + "And often is his gold complexion dimm'd,"
      + "And every fair from fair somtime declines,"
      + "By chance or nature's changing course untrimm'd:"
      + "But thy eternal summer shall not fade,"
      + "Nor lose possession of that fair thou ow'st,"
      + "Nor shall Death brag thou wand'rest in his shade,"
      + "When in eternal lines to time thou grow'st."
      + "\n  So long as men can breathe or eyes can see,"
      + "\n  So long lives this, and this gives life to thee.\n"
      + "William Shakespeare";
    return str;
  }

  public String getWatsonCrick() {
    String str =
      "J. D. WATSON and F. H. CRICK\n"
      + "A Structure for Deoxyribose Nucleic Acid\n"
      + "(From Nature, April 25, 1953, pp. 737-738)\n"
      + "\n  We wish to suggest a structure for the salt of deoxyribose nucleic "
      + "acid (D.N.A.). This structure has novel features which are of "
      + "considerable biological interest. "
      + "\n  A structure for nucleic acid has already been proposed by Pauling "
      + "and Corey [1]. They kindly made their manuscript available to us in "
      + "advance of publication. Their model consists of three intertwined "
      + "chains, with the phosphates near the fibre axis, and the bases on the "
      + "outside. In our opinion, this structure is unsatisfactory for two "
      + "reasons: (1) We believe that the material which gives the X-ray "
      + "diagrams is the salt, not he free acid. Without the acidic hydrogen "
      + "atoms it is not clear what forces would hold the structure together, "
      + "especially as the negatively charged phosphates near the axis will "
      + "repel each other. (2) Some of the van der Waals distances appear to be "
      + "too small.  Another three-chained structure has also been suggested "
      + "by Fraser (in the press). In his model the phosphates are on the "
      + "outside and the bases on the inside, linked together by hydrogen "
      + "bonds. This structure as describes is rather ill-defined, and for this "
      + "reason we shall not comment on it. "
      + "\n  We wish to put forward a radically different structure for the salt "
      + "of deoxyribose nucleic acid. This structure has two helical chains "
      + "each coiled round the same axis (see diagram). We have made the usual "
      + "chemical assumptions, namely, that each chain consists of phosphate "
      + "di-ester groups joining beta-D-deoxyribofuranose residues with 3',5' "
      + "linkages. The two chains (but not their bases) are related by a dyad "
      + "perpendicular to the fibre axis. Both chains follow right-handed "
      + "helices, but owing to the dyad the sequences of the atoms in the two "
      + "chains run in opposite directions. Each chain loosely resembles "
      + "Furberg's [2] model No. 1; that is, the bases are on the inside of the "
      + "helix and the phosphates on the outside. The configuration of the "
      + "sugar and the atoms near it is close to Furberg's 'standard "
      + "configuration', the sugar being roughly perpendicular to he attached "
      + "base. There is a residue on each chain every 3.4 A, in the "
      + "z-direction. We have assumed an angle of 36 between adjacent residues "
      + "in the same chain, so that the structure repeats after 10 residues on "
      + "each chain, that is after 34 A. The distance of a phosphorous atom "
      + "from the fibre axis is 10 A. As the phosphates are on the outside, "
      + "cations have easy access to them. "
      + "\n  The structure is an open one, and its water content is rather "
      + "hight. At lower water contents we would expect the bases to tilt so "
      + "that the structure could become more compact. "
      + "\n  The novel feature of the structure is the manner in which the two "
      + "chains are held together by the purine and pyrimidine bases. The "
      + "planes of the bases are perpendicular to the fibre axis. They are "
      + "joined together in pairs, a single bases from one chain being "
      + "hydrogen-bonded to a single base from the other chain, so that the two "
      + "lie side by side with identical z-coordinates. One of the pair must be "
      + "a purine and the other a pyrimidine for bonding to occur. The hydrogen "
      + "bonds are made as follows: purine position 1 to pyrimidine position 1; "
      + "purine position 6 to pyrimidine position 6. "
      + "\n  If it is assumed that the bases only occur in the structure in the "
      + "most plausible tautomeric forms (that is, with the keto rather than "
      + "the enol configurations), it is found that only specific pairs of "
      + "bases can bond together. These pairs are: adenine (purine) with "
      + "thymine (pyrimidine), and guanine (purine) with cytosine (pyrimidine). "
      + "\n  In other words, if an adenine forms one member of a pair, on either "
      + "chain then on these assumptions the other member must be thymine; "
      + "similarly for guanine and cytosine. The sequence of bases on a single "
      + "chain does not appear to be restricted in any way. However, if only "
      + "specific pairs of bases can be formed, it follows that if the sequence "
      + "of bases on one chain is given, then the sequence on the other chain "
      + "is automatically determined. "
      + "\n  It has been found experimentally [3,4] that the ratio of the amounts "
      + "of adenine to thymine, and the ratio of guanine to cytosine, are "
      + "always very close to unity for deoxyribose nucleic acid. "
      + "\n  It is probably impossible to build this structure with a ribose "
      + "sugar in place of the deoxyribose, as the extra oxygen atom would make "
      + "too close a van der Waals contact. "
      + "\n  The previously published X-ray data [5,6] on deoxyribose nucleic "
      + "acid a re insufficient for a rigorous test of our structure. So far as "
      + "we can tell, it is roughly compatible with the experimental data, but "
      + "it must be regarded as unproven until it has been checked against more "
      + "exact results. Some of these are given in the following "
      + "communications. We were not aware of the details of the results "
      + "presented there when we devised our structure, which rests mainly "
      + "though not entirely on published experimental data and stereochemical "
      + "arguments.  "
      + "\n  It has not escaped our notice that the specific pairing we have "
      + "postulated immediately suggests a possible copying mechanism for the "
      + "genetic material. "
      + "\n  Full details of the structure, including the conditions assumed in "
      + "building it, together with a set of co-ordinates for the atoms, will "
      + "be published elsewhere. "
      + "\n  We are much indebted to Dr. Jerry Donohue for constant advice and "
      + "criticism, especially on interatomic distances. We have also been "
      + "stimulated by a knowledge of the general nature of the unpublished "
      + "experimental results and ideas of Dr. M H. F. Wilkins, "
      + "D. R. E. Franklin and their co-workers at King's College, London. One "
      + "of us (J.D.W.) has been aided by a fellowship from the National "
      + "Foundation for Infantile Paralysis.\n"
      + "\n"
      + "Medical Research Council Unit for the  "
      + "\n  study of the Molecular Structure of  "
      + "\n  Biological Systems,\n"
      + "Cavendish Laboratory, Cambridge\n"
      + "April 2\n"
      + "\n"
      + "References"
      + "\n[1] Pauling, L. and Corey, R. B., Nature, 171, 346 (1953); "
      + "Proc. U.S. Nat. Acad. Sci., 39, 84 (1953). "
      + "\n[2] Furberg, S., Acta Chem. Scand., 6, 634 (1952). "
      + "\n[3] Chargaff, E., for references see Zamenhof, S., Brawerman, G., and "
      + "Chargaff, E., Biochim. et Biophys. Acta, 9, 402 (1952). "
      + "\n[4] Wyatt, G. R., J. Gen. Pysiol., 36, 201 (1952). "
      + "\n[5] Astbury, W. T., Symp. Soc. Exp. Biol. 1, Nucleic Acid, 66 "
      + "(Cambridge Univ. Press, 1947). "
      + "\n[6] Wilkins, M. H. F., and Randall, J. T., Biochem. et Biophys. Acta, "
      + "10, 192 (1953).";
    return str;
  }

  public String getAlignment() {
    String alignment = ">Human\n"
                       + "GTAAATATAGTTTAACCAAAACATCAGATTGTGAATCTGACAACAGAGGCTTACGACCCCTTATTTACC\n"
                       + ">Chimpanzee\n"
                       + "GTAAATATAGTTTAACCAAAACATCAGATTGTGAATCTGACAACAGAGGCTCACGACCCCTTATTTACC\n"
                       + ">Gorilla\n"
                       + "GTAAATATAGTTTAACCAAAACATCAGATTGTGAATCTGATAACAGAGGCTCACAACCCCTTATTTACC\n"
                       + ">Orangutan\n"
                       + "GTAAATATAGTTTAACCAAAACATTAGATTGTGAATCTAATAATAGGGCCCCACAACCCCTTATTTACC\n"
                       + ">Gibbon\n"
                       + "GTAAACATAGTTTAATCAAAACATTAGATTGTGAATCTAACAATAGAGGCTCGAAACCTCTTGCTTACC\n";

    return alignment;
  }

}